version: '3'
services:
  defender-zone:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # ONLY mount the data directory, not the entire app
      - defender-data:/app/data
    environment:
      - NODE_ENV=production
      # Set to 'true' to disable configuration interface for public deployments
      - DISABLE_CONFIG=false
    restart: unless-stopped

volumes:
  defender-data: